# Numpy cheatsheet

In [1]:
import numpy as np

## Reshape a tensor: np.transpose

Here is a toy array of shape (3,2,2).

In [2]:
arr = np.array([
    [
        [1,1],
        [2,2],        
    ],
    [
        [10,10],
        [20,20],        
    ],
    [
        [100,100],
        [200,200],        
    ],
]);arr.shape

(3, 2, 2)

Oftentimes different frameworks and libraries use different shape schemes and we need to rearrange elements within tensors. What do we do if we want to reshape `arr` to (2,2,3) i.e., the first axis would become the last axis.

In [11]:
arr_t = np.transpose(
    arr, axes=(1,2,0)
); 
arr_t.shape

(2, 2, 3)

Let's check the content.

In [4]:
arr_t

array([[[  1,  10, 100],
        [  1,  10, 100]],

       [[  2,  20, 200],
        [  2,  20, 200]]])

Let's validate if the manipulation has done right.

In [10]:
np.all(arr[0,:,:] == arr_t[:,:,0])

True

In [6]:
arr[0,:,:]

array([[1, 1],
       [2, 2]])

In [7]:
arr_t[:,:,0]

array([[1, 1],
       [2, 2]])